---
title: "CRM Simulations"
author: "Don van den Bergh"
date: "9/14/2021"
output: html_document
---

```{r setup, include=FALSE}
ragg_png = function(..., res = 192) {
  ragg::agg_png(..., res = res, units = "in")
}
knitr::opts_chunk$set(dev = "ragg_png", fig.ext = "png")
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r simulate}
library(CRMLogistic)

np <- 50             # no patients
ni <- 20             # no items
nr <- 30             # no raters
no_rater_groups <- 4 # no groups of rater

set.seed(1234)
dat <- simulate_data_crm(np, ni, nr, no_rater_groups = no_rater_groups)
head(dat$df)
summary(dat$df)
```

## Including Plots

You can also embed plots, for example:

```{r data heuristics}
data_2_init(dat$df) |>
  add_true_values_to_em_tib(dat) |>
  scatterplot_retrieval() +
  ggplot2::labs(x = "True value", y = "Estimate") +
  ggplot2::ggtitle("Initial parameter estimates based on data heuristics")
```
```{r fit EM, cache=TRUE}
em_tib <- fit_em(dat$df, record_all_iterations = 5, n_iter = 10, compute_locations_scales = TRUE)
```

```{r plot EM, fig.height=14}
em_tib |> add_true_values_to_em_tib(dat) |> scatterplot_retrieval(facets = iteration~parameter)
```


```{r fit vb, cache=TRUE}
# convert the data to something suited for cmdstanr
stan_data <- crm_data_2_stan(dat)
# extract initial values from em for vb
init <- list(em_tib_to_init(em_tib, dat))

mod <- CRMLogistic::compile_stan_model("stanmodels/extendedCRM_long_new_no_genq.stan")

# compile the model
vb_init_fit <- mod$variational(data = stan_data, iter = 3e4, grad_samples = 3, elbo_samples = 2, adapt_iter = 500, output_samples = 5e3,
                          init = init)
vb_init_tib <- get_means_tib(vb_init_fit, dat)
vb_init_tib |> scatterplot_retrieval() + ggtitle(sprintf("mod$variational informed by EM: %.3f seconds", vb_init_fit$time())) + labs(x = "Variational Estimate", y = "True value")

em_tib <- fit_em(dat$df, record_all_iterations = 5, n_iter = 10, compute_locations_scales = TRUE)
```

```{r plot vb, fig.height=14}
em_tib |> add_true_values_to_em_tib(dat) |> scatterplot_retrieval(facets = iteration~parameter)
```
