# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
get_probs_ordered_logistic_cpp <- function(thresholds, location, scale) {
    .Call('_CCTLogistic_get_probs_ordered_logistic_cpp', PACKAGE = 'CCTLogistic', thresholds, location, scale)
}

